spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: caresercizio12345
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
            

            logging:
  level:
    org:
      springframework: ERROR
    com:
      mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
